# Generated by Django 5.2.6 on 2025-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
