# Generated by Django 5.2.6 on 2025-10-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_v20state_alter_voter_v21primary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='precinct',
            new_name='precinct_number',
        ),
    ]
