# Generated by Django 5.2.6 on 2025-10-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_photo_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
    ]
